### ISSUE TITLE
Speed stat ups not taken into account when calculating first pokemon to move

### ISSUE THREAD

**Issue by Gindranis** [Zarel/honko-damagecalc#130]
Setting Speed to +2 does not alter the generated outcome.
Tested with various pokemon that carry a move that would deal 100%+ damage, but get outsped before +2 speed, such as cloyster vs tapu koko, Haxorus vs Garchomp, Gengar vs Alakazam

**Comment by MagiaSN** [comment]
I don't quite understand this issue, the speed stats do not affect the damage directly, so speed changes are not shown in the result message

If the power of the move depends on speed stats (e.g. Electro Ball), the changes is shown directly in move BP

If you mean "when setting Cloyster's speed to +2, then Icicle Spear should be automatically chosen instead of opposite Tapu Koko's Thunderbolt, because Cloyster should move first", it seems there is no such feature now, but I think the maintainers (@AustinXII)  would be glad to take it into consideration

**Comment by AustinXII** [comment]
Planned

**Comment by Ntonio36** [comment]
5 months later, I'm working on it. Probably done in like 20 days ? 

Regardless, expect big things to be changed.

**Comment by Ntonio36** [comment]
PR done.

**Comment by AustinXII** [comment]
fixed in #192
