### ISSUE TITLE
Update sets and commit set update script

### ISSUE THREAD

**Issue by scheibo** [Zarel/honko-damagecalc#343]
We should **include the set import logic in the codebase** so that any collaborator can update sets and we don't have to bug @Honko to run things for us (eg. #339). Alternatively, I will write a new set importer script and include it in the codebase.

On the topic of set imports, I received the following request via PM:

> I was wondering if you could include some sets from UM analyses (1v1, ZU, and AG), which have not been implemented for some reason, as other OMs such as Balanced Hackmons have their sets included in the calc.

**Does the script currently elide certain metagames from the analyses?** I think we should be including every set from the analyses on Smogon, however, to avoid having too many options available in the dropdown we probably want to tweak the UI. 

As mentioned in #333, we will likely want to add a format selector to separate out the Randbats calculator from the standard one. My proposed breakdown for modes is:

`Official | Unofficial | VGC | Randbats | BSS`

Where:

- `Official` includes sets from [Smogon's Core & Official Metagames](https://www.smogon.com/forums/threads/smogons-official-core-metagames.3513352/)
- `Unofficial` includes metagames established enough to have analyses on Smogon
- `VGC` includes sets for the VGC formats (+ autolevels to 50 and sets 'Doubles' mode by default)
- `Randbats` sets level based on random battles level, + EVs to 85 and other random battle features
- `BSS` - battle spot sets, auto level to 50, etc

`Official` vs. `Unofficial` formats are just to avoid the unofficial sets from cluttering the main UI, but if we're not super concerned with this we can just have a 'Standard' format for all level 100 non randomized sets.

I've assigned this to Honko because their currently the only one with access the set import script that we've been using. After the script has been committed (or, if Honko doesn't wish to commit the existing import script - after I add one) we can update it to split out the formats approriately and add a format selector.

**Comment by Honko** [comment]
> We should include the set import logic in the codebase so that any collaborator can update sets and we don't have to bug @Honko to run things for us (eg. #339). Alternatively, I will write a new set importer script and include it in the codebase.

I recommend writing a new one. Mine is written in Java, not because that's the right tool for the job but because it's what I was comfortable using at the time. It works, but it's bloated and full of lazy fixes I've added over the years. I'd be happy to review the new script and call out any funky edge cases that you might have missed.

> **Does the script currently elide certain metagames from the analyses?** I think we should be including every set from the analyses on Smogon, however, to avoid having too many options available in the dropdown we probably want to tweak the UI.

Yes, it currently uses a whitelist of metagames, for two reasons:
1) To avoid having too many options in the dropdown, particularly for abandoned metagames like old VGC formats.
1) To avoid importing sets for metagames that the calculator does not currently support, such as LGPE OU or Mix and Mega.

Your proposed UI change solves the first but not the second. I don't know how popular LGPE is as a format on PS, but since it's somewhat official it might be worth adding support for its custom mechanics (happiness boost, different base powers for certain moves) to the calculator as a separate mode. Other OMs that modify base stats, typings, etc like Mix and Mega or Averagemons seem less reasonable to try to support, but I'll leave that decision up to you.

For the specific metagames you were PMed about, ZU and AG are currently included, it's just been a couple months since the last run so some sets are probably missing. 1v1 isn't on the whitelist, but I will add it before the next time I run an import.

Finally, thanks for taking the initiative on this. I look forward to shedding this responsibility. :)

**Comment by scheibo** [comment]
@Honko: I'm currently working on this. Some questions that I already have:

1) How are the `'XX Showdown Usage'` sets populated?
2) What is your current whitelist of metagames?
3) I assume you're just taking the first option in every case where the Smogon moveset has slashes?
4) Smogon coallesces Megas in with base formes - I assume you pull out the sets where the mega item is used for the mega's movesets?

**Comment by Honko** [comment]
1. I pull the JSON moveset stats from the latest month's `/chaos/` directory under `https://www.smogon.com/stats/` for all the current gen mainline tiers (OU/UU/RU/NU/PU/ZU, Ubers, LC, and Doubles OU). I use the highest available weighted ladder (1825 for OU and Doubles OU, 1760 for everything else). I don't do anything fancy, just take the top 4 moves, top item, top ability, top nature, and top EVs, without checking whether those all fit well together. Since I intended these to be placeholders for important Pokemon that are missing analyses, I only include a Pokemon's usage-based set for a metagame if (1) they have no analysis for that metagame and (2) they reached at least 1% usage in the metagame that month (3% in Ubers and Doubles OU because they have notoriously bad ladders). In addition to current gen mainline tiers, I also include usage-based sets from the following old rotational ladders for old gen lower tiers that have very few analyses on Smogon:
    * http://www.smogon.com/stats/2017-12/chaos/gen1uu-1500.json
    * http://www.smogon.com/stats/2016-08/chaos/gen2uu-1500.json
    * http://www.smogon.com/stats/2018-11/chaos/gen2nu-1500.json
    * http://www.smogon.com/stats/2016-11/chaos/gen3uu-1500.json
    * http://www.smogon.com/stats/2016-09/chaos/gen3nu-1500.json
    * http://www.smogon.com/stats/2016-10/chaos/gen4nu-1500.json
1. Uber, OU, UU, RU, NU, PU, ZU, LC, Doubles OU, VGC18, Battle Spot Singles, Battle Spot Doubles, Anything Goes, Balanced Hackmons, Monotype, 1v1, and CAP. The last four are only whitelisted for the current gen.
1. Correct. In the past I used to try to flatten movesets more intelligently to include as many attacking moves as possible, but I stopped doing that when we started including non-attacking moves in the calculator since people wanted to see the actual recommended sets. I'm still unsure whether that was a good change.
1. Correct. In addition to the regular Megas, the other cases where I duplicate sets for alt formes are: Groudon/Kyogre-Primal with Red/Blue Orb, Rayquaza-Mega with Dragon Ascent in non-Ubers tiers, Greninja-Ash with Battle Bond, Zygarde-Complete with Power Construct, Meloetta-Pirouette with Relic Song (though idt this one gets used), and Necrozma-Ultra with Ultranecrozium Z.

**Comment by scheibo** [comment]
@Honko - Did you give me the correct link for Gen 2 NU? I have a comparison script for my output vs. what's currently checked in, and other than Gen 2 NU Showdown Usage sets we match (modulo sets which have changed since you last ran it and with bugs in your output corrected by my script).

For posterity, this is what I'm using to compare:

```js
const fs = require('fs');
const path = require('path');

const JSON5 = require('json5');
const diff = require('json-diff')

const ACTUAL = 'tmp/sets';
const EXPECTED = '../src/js/data/sets';

const gen = process.argv[2];

const actual = JSON.parse(fs.readFileSync(path.resolve(__dirname, ACTUAL, `gen${gen}.json`), 'utf8'));
const raw = fs.readFileSync(path.resolve(__dirname, EXPECTED, `gen${gen}.js`), 'utf8');
const expected = JSON5.parse(raw.match(/var.*?=.*?({.*})/s)[1]);

console.log(diff.diffString(actual, expected));
```
