### ISSUE TITLE
Rotom forms have lost their sets

### ISSUE THREAD

**Issue by sobolews** [Zarel/honko-damagecalc#57]
The various Rotom forms no longer have sets. For me, their sets used to show up until I cleared my cache for that page, so this is probably due to a recent change. The normal Rotom forme still has sets.

Screenshot: http://i.imgur.com/SLfGAal.png

**Comment by sobolews** [comment]
This occurs for Landorus-T, Mr. Mime, etc. too, so it's probably just a parsing issue with `-.` characters.

**Comment by Honko** [comment]
Oops, this was a problem with my latest import. Actually two problems:

1) The Smogon API doesn't like the raw names of Pokemon with punctuation (Mr. Mime, Farfetch'd) so I didn't import any sets for them
2) The forme name format for Pokemon like Rotom and Landorus is different from what I used in the pokedex so their sets are imported under the wrong name (Landorus-Therian instead of Landorus-T) and therefore not showing up in the calc.

I'll fix this today.

**Comment by AustinXII** [comment]
This seems to be fixed and should probably be closed as an issue
